-- phpMyAdmin SQL Dump
-- version 5.0.2
-- https://www.phpmyadmin.net/
--
-- Hôte : 127.0.0.1:3306
-- Généré le : mer. 22 sep. 2021 à 03:43
-- Version du serveur :  8.0.21
-- Version de PHP : 7.3.21

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Base de données : `td_symfony_db`
--

--
-- Déchargement des données de la table `article`
--

INSERT INTO `article` (`id`, `title`, `text_content`, `category_id`, `user_profil_id`, `published_at`) VALUES
(1, 'Sed varius tortor a diam.', 'In imperdiet, lacus in venenatis vestibulum, mauris nulla dapibus risus, quis sagittis sapien massa eu ante. Fusce quis hendrerit nisl. Quisque sed metus massa. Morbi non feugiat dolor, at dignissim odio. Vestibulum tincidunt augue id suscipit condimentum. Fusce urna sapien, vestibulum viverra laoreet ut, viverra ut enim. Pellentesque efficitur est elit, quis feugiat est varius sed. Aenean scelerisque tortor ut luctus laoreet. Praesent tempor, dui a dignissim malesuada, dolor elit mollis mauris, vel commodo dui quam ut risus. Pellentesque ultrices feugiat libero, sed porta nulla pulvinar eget.\r\n\r\nSed in est ac purus laoreet accumsan in eu elit. Fusce non nibh non est dapibus ornare nec et ipsum. Nunc odio erat, condimentum in ante quis, euismod consequat nunc. Duis ut tellus leo. Proin sit amet erat nisl. Praesent tempor ligula sem, ut bibendum orci bibendum in. In urna augue, vulputate at neque a, aliquam pellentesque ante. Proin non pharetra velit. Nullam tristique diam eu tincidunt facilisis. Curabitur laoreet, risus non luctus auctor, quam massa pellentesque arcu, eget maximus ante dolor vitae tellus. Phasellus id posuere libero, vel vulputate dolor. Donec sem felis, placerat quis tincidunt a, accumsan quis odio. Nam auctor orci massa, id malesuada nisi imperdiet at. Cras tincidunt tincidunt sem, non finibus magna interdum non.\r\n\r\nAliquam sit amet mattis neque. Proin vehicula, eros tincidunt tincidunt vehicula, massa dui vehicula augue, nec tristique ante nisl vel massa. Nullam fermentum nulla malesuada, ultrices nulla a, pretium elit. Vestibulum eu lectus quis sem maximus feugiat. Integer sed turpis eleifend, vestibulum sapien eu, hendrerit nisl. Nunc arcu mi, efficitur in ante ut, sodales hendrerit mi. Praesent tempus massa vitae neque pellentesque, vel pharetra lectus pellentesque. Praesent nulla massa, ornare id tincidunt a, laoreet ac erat. Mauris mattis ac tellus consectetur dignissim. Nunc quis nisl vel massa ultrices consectetur. Sed et neque varius mi pellentesque suscipit quis aliquet quam.\r\n\r\nProin elementum congue vulputate. Maecenas id ornare ligula. Nulla tristique lacus sed sem venenatis, eu sagittis lectus rutrum. Quisque laoreet ultricies lacus, sit amet pellentesque dolor pharetra et. Proin turpis leo, convallis sed ultrices in, porta non ante. In id gravida dui. Mauris metus elit, convallis aliquam tincidunt in, rutrum non tortor. Sed vel erat nisi.', 9, 2, '2021-09-18 05:37:46'),
(2, 'Aenean faucibus urna massa', 'Vivamus dictum libero quam, vitae convallis lorem pretium ullamcorper. Fusce ullamcorper gravida ex quis euismod. Vestibulum tempor viverra neque id bibendum. Aliquam at suscipit nulla, eget auctor ligula. Quisque convallis pharetra sem quis pharetra. Fusce laoreet mollis porta. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; In ut vulputate arcu, ac euismod massa. Proin mattis orci quis lacus imperdiet mollis. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Suspendisse mattis aliquam ullamcorper. Cras nec quam eget lacus mollis dignissim ut a urna. Vestibulum quis dui placerat, sollicitudin velit et, fermentum velit. Nulla et odio non neque tempor efficitur. Curabitur pretium urna non metus suscipit consectetur. Duis et tellus tempor, scelerisque lacus congue, tempus nisl.\r\n\r\nMaecenas vel ipsum quis est vehicula dapibus. Interdum et malesuada fames ac ante ipsum primis in faucibus. Integer pellentesque vitae enim sit amet imperdiet. Duis egestas, dui vitae sagittis vestibulum, libero augue faucibus est, in accumsan metus quam bibendum lacus. Donec nec molestie enim. Nulla vitae nulla tempus felis lobortis aliquam in vel metus. Nam rutrum tellus eget massa scelerisque aliquet. Suspendisse tempus blandit sem, non pellentesque turpis dapibus sed. Donec purus magna, elementum vitae magna id, consectetur pharetra est.\r\n\r\nSuspendisse potenti. Interdum et malesuada fames ac ante ipsum primis in faucibus. Ut eget lorem ut elit lobortis tincidunt ac gravida augue. Aenean aliquam molestie velit, eu fermentum nibh vehicula vitae. Vestibulum feugiat erat eu facilisis egestas. Integer eget rutrum turpis, at dictum nibh. Aenean tristique, metus ac finibus fermentum, diam sapien tempor lacus, at condimentum felis dolor nec mi. Etiam ultrices vitae nunc ut luctus. Nulla et lorem sed lectus rutrum convallis. In tortor lacus, fringilla id quam ac, aliquet cursus justo. Vestibulum sit amet diam aliquam, tincidunt leo at, euismod justo. Ut luctus tristique velit, sit amet dapibus ligula lobortis non. Mauris vehicula facilisis lorem, eget pretium turpis mollis facilisis. Fusce feugiat et eros et facilisis. Cras sed turpis libero. Nam tempor posuere tempor.', 3, 1, '2021-09-19 05:37:46'),
(3, 'Nullam dictum felis', 'Curabitur commodo dolor eu odio finibus, id elementum mauris blandit. Nam at libero augue. Curabitur vel orci vel ipsum elementum vulputate sit amet sed massa. Fusce in mollis sapien. Suspendisse sed gravida leo, vitae rutrum mauris. Vivamus faucibus nulla id mauris imperdiet convallis. Aliquam erat volutpat. Nulla gravida congue dolor eget viverra. Mauris suscipit consectetur diam porta faucibus.\r\n\r\nIn neque nisl, egestas in ultricies vitae, viverra in leo. Etiam odio est, lobortis id metus in, tempus sagittis neque. Sed lacus nisi, vestibulum nec tincidunt sed, semper sit amet felis. Sed quis blandit mauris, in tempus quam. Fusce vulputate dui consectetur quam rutrum, sed imperdiet risus hendrerit. Quisque consequat finibus neque, non scelerisque quam scelerisque vitae. Vivamus nibh ex, semper vel nibh vel, sollicitudin accumsan elit. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Nulla ut ultrices lectus. Duis scelerisque vitae mi et finibus. Phasellus aliquam nec massa ac pharetra.\r\n\r\nUt vehicula tincidunt finibus. Vestibulum egestas a ligula vel luctus. Suspendisse ac nunc quis nisi tincidunt faucibus non nec augue. Aliquam at nunc vel metus venenatis iaculis non vitae sapien. Sed imperdiet justo ac dui venenatis, vel pretium augue ornare. Phasellus euismod auctor eros eget vulputate. Ut nibh eros, vulputate non tortor non, vestibulum sodales leo. Proin augue turpis, sagittis quis blandit eget, imperdiet sed orci. Donec convallis, enim nec sollicitudin egestas, augue metus auctor sem, at fringilla ligula magna at leo. Donec dolor velit, blandit non vehicula ut, vehicula vitae sapien. Proin vehicula lectus at dolor hendrerit euismod. Nam congue erat ut erat posuere, et posuere ex consequat. Aenean convallis dolor id nulla molestie facilisis.\r\n\r\nSed ex felis, tristique rutrum arcu vel, efficitur porta purus. Duis commodo eleifend quam. Sed non sem imperdiet, tincidunt eros eu, consectetur urna. Fusce gravida varius lorem et condimentum. Ut egestas neque at magna mattis scelerisque. Phasellus sit amet leo leo. Quisque ultricies efficitur dui eu tempor. Integer mattis ex cursus, condimentum diam ut, tincidunt ex. Quisque tempor nisl erat, ac lobortis diam imperdiet in. Maecenas eleifend felis ornare libero sollicitudin vulputate. Etiam tristique turpis at malesuada sodales. Pellentesque molestie tristique elementum.', 2, 1, '2021-09-20 05:37:46'),
(4, 'Maecenas interdum ultricies risus', 'Vestibulum at nibh ac lectus commodo pharetra. Vivamus lorem justo, consectetur at ullamcorper vitae, ornare sit amet ligula. Quisque ut eros vel felis aliquam fermentum quis non dolor. Fusce dapibus odio vitae luctus scelerisque. Cras non augue sit amet turpis congue pretium. Nulla euismod ultrices feugiat. Nam imperdiet tortor odio, ac sagittis tellus facilisis nec. Curabitur nec tincidunt neque. Nullam pharetra turpis odio, id posuere lacus fermentum ac. Maecenas magna justo, scelerisque eget tincidunt in, luctus ut nisl. Donec eget ante tellus. Maecenas dignissim blandit eros, eget volutpat ex vulputate eget. Suspendisse dapibus rhoncus malesuada. Sed posuere, ante venenatis elementum vestibulum, ligula mi rutrum leo, vel semper urna magna vel eros.\r\n\r\nMaecenas diam diam, luctus non vulputate nec, vehicula ut enim. Duis vestibulum volutpat dolor, id iaculis lacus feugiat sed. Suspendisse et ante ut sapien sollicitudin dapibus sed eu dolor. Nulla ligula purus, pharetra quis ipsum et, lobortis vestibulum nulla. Fusce at sollicitudin est. Donec eu ex eu ante tempor sollicitudin. Pellentesque non scelerisque nisl, eu condimentum massa. Nulla maximus id enim non posuere. Etiam aliquet porta nibh, sit amet vulputate nisi malesuada ac. Fusce nec erat venenatis, sagittis felis in, viverra nibh.\r\n\r\nMaecenas elementum eu nisl nec elementum. Quisque ac arcu eu augue hendrerit tincidunt sed sed lectus. Cras risus lectus, scelerisque sed est et, consequat luctus purus. Morbi ornare sodales faucibus. Quisque lacus lacus, pharetra ac libero id, scelerisque viverra neque. Morbi sed massa aliquet, dictum metus a, sollicitudin augue. Curabitur sed sagittis ligula. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Donec venenatis orci nec lorem congue, quis eleifend sem faucibus. Curabitur convallis orci vitae consequat luctus. Ut et tortor eget dui consectetur sollicitudin. Cras rhoncus leo eget accumsan tincidunt. Ut commodo, enim ornare vestibulum consectetur, tortor est viverra quam, a accumsan lectus ex in mauris. Etiam metus dui, suscipit nec magna non, laoreet sodales mi. Ut id consectetur enim. Cras non euismod dolor.', 1, 2, '2021-09-21 05:37:46');
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
